version: '2.4'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: golang_api
      POSTGRES_DB: golang_api
    volumes:
      - data:/var/lib/postgresql/data/

volumes:
  data:
